### ISSUE TITLE
Can SQLiteDatabase accept pathlib objects?

### ISSUE THREAD

**Issue by paulrougieux** [xapple/plumbing#4]
# Current status

```
ipdb> db_v1 = SQLiteDatabase(db_path_v1)
*** TypeError: argument of type 'PosixPath' is not iterable
ipdb> str(db_path_v1)
'/home/paul/repos/eu_cbm/eu_cbm_aidb/countries/SI/aidb_v1.db'
```

Longer stack trace of the error in that case:

```
File ~/eu_cbm/eu_cbm_hat/scripts/conversion/update_aidb_1x_to_2x.py:66, in convert_aidb_to_v2(db_path)
     64 # Rename the old AIDB to v1
     65 shutil.copy(db_path, db_path_v1)
---> 66 # Remove the "index" column in the disturbance_matrix_value table.
     67 # This was introduced by mistake and shouldn't be there.
     68 db_v1 = SQLiteDatabase(db_path_v1)
     69 dm_values = db_v1.read_df("disturbance_matrix_value")

File ~/repos/autopaths/autopaths/base_path.py:60, in BasePath.__new__(cls, path, *args, **kwargs)
     58 def __new__(cls, path, *args, **kwargs):
     59     """A Path object is in fact a string."""
---> 60     return str.__new__(cls, cls.clean_path(path))

File ~/repos/autopaths/autopaths/base_path.py:38, in BasePath.clean_path(cls, path)
     36 if hasattr(path, 'path'): path = path.path
     37 # Expand the tilda #
---> 38 if "~" in path: path = os.path.expanduser(path)
     39 # We will store the path with the OS specific separator #
     40 # We will never mix both kinds of separators #
     41 if os.name == "posix": path = path.replace("\\", sep)

TypeError: argument of type 'PosixPath' is not iterable
```

Easily fixed by converting to a string
```
ipdb> db_v1 = SQLiteDatabase(str(db_path_v1))
```

But the error message "TypeError: argument of type 'PosixPath' is not iterable" is confusing at first. 

# Proposal

The "argument of type 'PosixPath' is not iterable" is a bit confusing. Can SQLiteDatabase accept pathlib objects?

**Comment by xapple** [comment]
This is an issue with the `autopaths` project, and not `plumbing` per se.

The idea used there is that a path is a string of characters (with extra conveniance methods), but for some reason the `PosixPath` object from `pathlib` does not inherit from `str` and has a different nature. I always thought that was a very bad design decision.

You should submit a pull request to `autopaths` that checks that the argument is indeed a string, and reports a better error message when it is not. Or alternatively tries to cast the argument to a string and continue.
